"""add token column to users

Revision ID: 92bd74acb79f
Revises: 897b1493b857
Create Date: 2025-07-15 16:14:32.060354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '92bd74acb79f'
down_revision: Union[str, Sequence[str], None] = '897b1493b857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Add column first
    op.add_column('users', sa.Column('token', sa.String(length=255), nullable=True))

    # If needed, set all existing tokens to NULL explicitly
    op.execute("UPDATE users SET token = NULL")

    # Then add the unique index
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=True)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=20),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
