"""add_description_and_user_id_to_reactflow

Revision ID: 9fba29f442ad
Revises: 
Create Date: 2025-08-04 18:07:20.791663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9fba29f442ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reactflow_email'), table_name='reactflow')
    op.drop_index(op.f('ix_reactflow_id'), table_name='reactflow')
    op.drop_index(op.f('ix_reactflow_phone'), table_name='reactflow')
    op.drop_index(op.f('ix_reactflow_token'), table_name='reactflow')
    op.drop_table('reactflow')
    op.add_column('reactflows', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('reactflows', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reactflows', 'user_id')
    op.drop_column('reactflows', 'description')
    op.create_table('reactflow',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_reactflow_token'), 'reactflow', ['token'], unique=True)
    op.create_index(op.f('ix_reactflow_phone'), 'reactflow', ['phone'], unique=True)
    op.create_index(op.f('ix_reactflow_id'), 'reactflow', ['id'], unique=False)
    op.create_index(op.f('ix_reactflow_email'), 'reactflow', ['email'], unique=True)
    # ### end Alembic commands ###
