"""your message here

Revision ID: dadfde363534
Revises: 00c25a8daea2
Create Date: 2025-07-09 17:47:36.643898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dadfde363534'
down_revision: Union[str, Sequence[str], None] = '00c25a8daea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
